### ISSUE TITLE
Set up the basics

### ISSUE THREAD

**Issue by d0ty** [Engame-Coding-Society/engame-quiz#1]
# Definition of the questions
In a quiz game everything goes around the questions themselves. So first we need to define a structure for them.
We'll have a `Question` class inside of the `question.py` file with the following properties:
- `question`: The text of the question what we'll show later in the game. For example `"A, B, or C?"` or `"Who is a Student Recruitment Manager at Engame?"`
- `options`: The list of the possible answers. For example: `['A', 'B', 'C']` or `['Anna Iglódi', 'Peti Násztor', 'Virág Keresztes']`.
- `correctIdx`: The index of the correct answer. It points to the answer from the list what we mark as the solution. For example for the first question the answer is 'A', so our `correctIdx` will be 0. For the second question the answer is 'Virág Keresztes', so the `correctIdx` property will be 2. An so on...

If you're done, please open a pull request!

**Comment by d0ty** [comment]
When I wrote the code, I realized `correctIdx` wasn't so correct name for this variable so I renamed it to `correct_idx`

**Comment by EndergamerHUN** [comment]
I can suggest linking the __init__ function with a py documentation reference using :func:`__init__`

**Comment by d0ty** [comment]
Okay. To this in your next task, in a separated commit. And please refer this issue in your pull request where you submit this change.
