### ISSUE TITLE
Randomize the questions

### ISSUE THREAD

**Issue by d0ty** [Engame-Coding-Society/engame-quiz#4]
Create an array randomization algorythm into the `randomization.py` script. For testing, create a script called `test_random.py` into the `tests` folder. Write a simple test here with 10 random question instance (import it from `question.py` from the parent dir.

Feel free to ask from me any time. Just leave a comment below this issue.

**Comment by d0ty** [comment]
Hello! 
While I was planning #8 it considered, we need an exclude-list of question indexes what we asked before we get a random question.
Can you do this in this issue?

**Comment by yefetk** [comment]
I'll try

**Comment by d0ty** [comment]
Or we can stay with we random reorder the whole question array and then we don't need to strugle around the exclusion. What do you want?
